#!/bin/sh

#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
set -o errexit # Exit on error
set -o nounset # Exit on unset variables

SCRIPT_DIR=$(dirname "$0")

cd ${SCRIPT_DIR} || exit  # SCRIPT_DIR points at bin
cd .. # now SCRIPT_DIR points at parent dir for bin

# if IGNITE_HOME is not set than it will be parent directory for bin
if [ -z ${IGNITE_HOME+x} ]; then IGNITE_HOME=$(pwd); fi

DEFAULT_NODE_NAME=defaultNode

# Set default values based on IGNITE_HOME
DEFAULT_WORK_DIR="@WORK_DIR@"
DEFAULT_LOG_DIR="@LOG_DIR@"
DEFAULT_LIBS_DIR="@LIB_DIR@"
DEFAULT_CONFIG_DIR="@CONF_DIR@"
DEFAULT_CONFIG_NAME="@CONF_NAME@"
DEFAULT_EXTRA_JVM_ARGS=

# Check if environment variables are set and prioritize them over command-line options
export IGNITE_NODE_NAME="${IGNITE_NODE_NAME:-${DEFAULT_NODE_NAME}}"
export IGNITE_WORK_DIR="${IGNITE_WORK_DIR:-${DEFAULT_WORK_DIR}}"
# TODO https://issues.apache.org/jira/browse/IGNITE-24812
# export IGNITE_LOG_DIR="${IGNITE_LOG_DIR:-${DEFAULT_LOG_DIR}}"
export IGNITE_LOG_DIR="${DEFAULT_LOG_DIR}"
export IGNITE_LIBS_DIR="${IGNITE_LIBS_DIR:-${DEFAULT_LIBS_DIR}}"
export IGNITE_CONFIG_DIR="${IGNITE_CONFIG_DIR:-${DEFAULT_CONFIG_DIR}}"
export IGNITE_CONFIG_FILE="${IGNITE_CONFIG_FILE:-${IGNITE_CONFIG_DIR}/${DEFAULT_CONFIG_NAME}}"
export IGNITE_EXTRA_JVM_ARGS="${IGNITE_EXTRA_JVM_ARGS:-${DEFAULT_EXTRA_JVM_ARGS}}"

. ${IGNITE_CONFIG_DIR}/@VARS_FILE_NAME@
. ${IGNITE_LIBS_DIR}/@BOOTSTRAP_FILE_NAME@

cd ${IGNITE_HOME} || exit

CMD="${JAVA_CMD_WITH_ARGS} ${APPLICATION_ARGS}"
$CMD
